scss_files: "src/scss/**/*.scss"

linters:
  LeadingZero:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  ElsePlacement:
    enabled: true
    style: new_line
  SelectorFormat:
    convention: hyphenated_BEM
  NestingDepth:
    max_depth: 10
  SelectorDepth:
    max_depth: 10
  Indentation:
    character: tab
    width: 1
  QualifyingElement:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  StringQuotes:
    style: double
  Comment:
    enabled: false
  HexLength:
    style: long
  FinalNewline:
    enabled: false
